import { useState, useEffect, useCallback, useRef } from "react";
import {
  FaFloppyDisk,
  FaRotateLeft,
  FaFile,
  FaFileCode,
  FaFilePen,
  FaCircleExclamation,
  FaCircleInfo,
} from "react-icons/fa6";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { CodeMirrorEditor } from "@/components/ui/code-editor";
import { useBackend } from "@/hooks/useBackend";
import { useWebSocket } from "@/hooks/useWebSocket";
import { toastSuccess } from "@/lib/toast";
import { getConfigEditor } from "@/components/server-details/games/registry";
import type { GameServer } from "@/types";

interface FileState {
  rawContent: string;
  originalContent: string;
  hasChanges: boolean;
  loaded: boolean;
}

interface ConfigTabProps {
  server: GameServer;
  onRefresh?: () => void;
}

export function ConfigTab({ server, onRefresh }: ConfigTabProps) {
  const { api, isConnected } = useBackend();
  const { subscribe } = useWebSocket();
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [configFiles, setConfigFiles] = useState<string[]>([]);
  const [activeFile, setActiveFile] = useState<string>("");
  const fileStates = useRef<Map<string, FileState>>(new Map());
  // Force re-render when fileStates change
  const [, setRenderKey] = useState(0);

  // Initial mode: config not yet generated by the game (e.g. ARK first start)
  const [initialMode, setInitialMode] = useState(false);
  const [checkingConfigStatus, setCheckingConfigStatus] = useState(true);

  const loadFile = useCallback(
    async (fileName?: string) => {
      setLoading(true);
      setError(null);
      try {
        const data = await api.servers.getConfig(server.id, fileName);

        // Set available config files from first response, filtering out directory entries
        if (data.configFiles && data.configFiles.length > 0) {
          setConfigFiles(
            data.configFiles.filter((f: string) => !f.endsWith("/")),
          );
        } else if (configFiles.length === 0) {
          setConfigFiles([data.fileName]);
        }

        const targetFile = data.fileName;
        fileStates.current.set(targetFile, {
          rawContent: data.content,
          originalContent: data.content,
          hasChanges: false,
          loaded: true,
        });

        if (!activeFile) {
          setActiveFile(targetFile);
        }
        setRenderKey((k) => k + 1);
      } catch (err) {
        setError((err as Error).message);
      } finally {
        setLoading(false);
      }
    },
    [server.id, api.servers, activeFile, configFiles.length],
  );

  useEffect(() => {
    if (!isConnected) return;

    // Check config status first — determines whether to show initial mode.
    // Re-runs when server status changes so that after the first start
    // completes (starting → running) we pick up the newly generated configs.
    async function checkStatus() {
      setCheckingConfigStatus(true);
      try {
        const status = await api.servers.getConfigStatus(server.id);
        if (!status.configGenerated) {
          setInitialMode(true);
          setCheckingConfigStatus(false);
          setLoading(false);
          return;
        }
      } catch {
        // If endpoint fails (e.g. older agent), fall through to normal load
      }
      setInitialMode(false);
      setCheckingConfigStatus(false);
      loadFile();
    }
    checkStatus();
  }, [isConnected, server.id, server.status]); // eslint-disable-line react-hooks/exhaustive-deps

  // Listen for config-ready WebSocket event (after first start generates configs)
  useEffect(() => {
    const unsub = subscribe((msg) => {
      if (msg.type === "server:config-ready") {
        const payload = msg.payload as { serverId?: number } | undefined;
        if (payload?.serverId === server.id) {
          setInitialMode(false);
          loadFile();
        }
      }
    });
    return unsub;
  }, [subscribe, server.id, loadFile]);

  function handleFileSwitch(fileName: string) {
    setActiveFile(fileName);
    const state = fileStates.current.get(fileName);
    if (!state?.loaded) {
      loadFile(fileName);
    }
  }

  function handleContentChange(content: string) {
    const state = fileStates.current.get(activeFile);
    if (state) {
      state.rawContent = content;
      state.hasChanges = true;
      setRenderKey((k) => k + 1);
    }
  }

  async function handleSave() {
    const state = fileStates.current.get(activeFile);
    if (!state) return;

    setSaving(true);
    setError(null);
    try {
      await api.servers.saveConfig(server.id, state.rawContent, activeFile);
      state.originalContent = state.rawContent;
      state.hasChanges = false;
      toastSuccess("Configuration saved successfully");
      setRenderKey((k) => k + 1);
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setSaving(false);
    }
  }

  function handleReset() {
    const state = fileStates.current.get(activeFile);
    if (state) {
      state.rawContent = state.originalContent;
      state.hasChanges = false;
      setRenderKey((k) => k + 1);
    }
  }

  const currentState = fileStates.current.get(activeFile);
  const anyUnsaved = Array.from(fileStates.current.values()).some(
    (s) => s.hasChanges,
  );

  if (
    (loading || checkingConfigStatus) &&
    !currentState?.loaded &&
    !initialMode
  ) {
    return (
      <Card>
        <CardContent className="py-8 text-center text-muted-foreground">
          Loading configuration...
        </CardContent>
      </Card>
    );
  }

  // Initial mode: game hasn't generated configs yet (e.g. ARK before first start)
  if (initialMode) {
    const Editor = getConfigEditor(server.gameId);
    return (
      <div className="space-y-4">
        <Alert>
          <FaCircleInfo className="h-4 w-4" />
          <AlertDescription>
            The game server hasn't generated its configuration files yet.
            Configure the initial settings below, then start the server. After
            the first start completes, the full configuration editor will become
            available.
          </AlertDescription>
        </Alert>
        {Editor ? (
          <Editor
            rawContent=""
            originalContent=""
            onContentChange={() => {}}
            fileName=""
            initialMode
            serverId={server.id}
            launchParams={server.launchParams || ""}
            onLaunchParamsChange={onRefresh}
            serverName={server.name}
          />
        ) : (
          <Card>
            <CardContent className="py-8 text-center text-muted-foreground">
              Start the server once to generate configuration files, then return
              here to edit them.
            </CardContent>
          </Card>
        )}
      </div>
    );
  }

  if (error && !currentState?.rawContent) {
    return (
      <Card>
        <CardContent className="py-8">
          <Alert variant="destructive">
            <FaCircleExclamation className="h-4 w-4" />
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        </CardContent>
      </Card>
    );
  }

  const isRunning = server.status === "running";
  const hasMultipleFiles = configFiles.length > 1;

  return (
    <div className="space-y-6">
      {/* Messages */}
      {error && (
        <Alert variant="destructive">
          <FaCircleExclamation className="h-4 w-4" />
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      {/* Config Editor */}
      {currentState && (
        <Tabs defaultValue="form">
          <div className="flex flex-wrap items-center justify-between gap-3 sticky top-0 z-10 bg-background/95 backdrop-blur-sm py-2 -mt-2">
            <div className="flex items-center gap-3">
              {/* File selector dropdown for multi-file games */}
              {hasMultipleFiles && (
                <Select value={activeFile} onValueChange={handleFileSwitch}>
                  <SelectTrigger className="w-auto min-w-[180px] gap-2">
                    <FaFile className="h-3.5 w-3.5 text-ring/70 shrink-0" />
                    <SelectValue />
                    {currentState.hasChanges && (
                      <span className="h-2 w-2 rounded-full bg-yellow-500 shrink-0" />
                    )}
                  </SelectTrigger>
                  <SelectContent>
                    {configFiles.map((file) => {
                      const state = fileStates.current.get(file);
                      return (
                        <SelectItem key={file} value={file}>
                          <span className="flex items-center gap-2">
                            {file}
                            {state?.hasChanges && (
                              <span className="h-2 w-2 rounded-full bg-yellow-500" />
                            )}
                          </span>
                        </SelectItem>
                      );
                    })}
                  </SelectContent>
                </Select>
              )}

              <TabsList>
                <TabsTrigger value="form" className="gap-2">
                  <FaFilePen className="h-4 w-4 text-ring/70" />
                  Form Editor
                </TabsTrigger>
                <TabsTrigger value="raw" className="gap-2">
                  <FaFileCode className="h-4 w-4 text-ring/70" />
                  Raw Editor
                </TabsTrigger>
              </TabsList>
            </div>
            <div className="flex items-center gap-2">
              {(currentState.hasChanges || anyUnsaved) && (
                <Badge variant="warning">Unsaved Changes</Badge>
              )}
              {isRunning && (
                <Badge variant="destructive">Restart required</Badge>
              )}
              <Button
                variant="outline"
                size="sm"
                onClick={handleReset}
                disabled={!currentState.hasChanges || saving}
              >
                <FaRotateLeft className="h-4 w-4 mr-2" />
                Reset
              </Button>
              <Button
                size="sm"
                onClick={handleSave}
                disabled={!currentState.hasChanges || saving || isRunning}
              >
                <FaFloppyDisk className="h-4 w-4 mr-2" />
                {saving ? "Saving..." : "Save"}
              </Button>
            </div>
          </div>

          <TabsContent value="form" className="space-y-4">
            {(() => {
              const Editor = getConfigEditor(server.gameId);
              return Editor ? (
                <Editor
                  rawContent={currentState.rawContent}
                  originalContent={currentState.originalContent}
                  onContentChange={handleContentChange}
                  fileName={activeFile}
                  serverId={server.id}
                  launchParams={server.launchParams ?? undefined}
                  onLaunchParamsChange={onRefresh}
                />
              ) : (
                <Card>
                  <CardContent className="py-8 text-center text-muted-foreground">
                    No form editor available for this game. Use the Raw Editor
                    tab.
                  </CardContent>
                </Card>
              );
            })()}
          </TabsContent>

          <TabsContent value="raw">
            <div className="rounded-md border overflow-hidden h-[calc(100vh-18rem)] min-h-[300px]">
              <CodeMirrorEditor
                content={currentState.rawContent}
                originalContent={currentState.originalContent}
                fileName={activeFile}
                onContentChange={handleContentChange}
                onSave={
                  isRunning
                    ? undefined
                    : () => {
                        handleSave();
                      }
                }
                className="h-full"
              />
            </div>
          </TabsContent>
        </Tabs>
      )}
    </div>
  );
}
